name: Release Auto

on:
  workflow_call:

jobs:
  coditory-check:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check.outputs.release }}
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required to deduce version from git tags
          fetch-depth: 0

      - name: Version
        id: version
        uses: coditory/version-action@v1
        with:
          snapshot: ${{ inputs.snapshot }}
          manual-version: ${{ inputs.version }}
          increment-section: ${{ inputs.section }}

      - name: Check commits
        id: check
        env:
          LAST_VERSION_TAG: "v${{ steps.version.outputs.version }}"
          DEPENDABOT_AUTHOR: ""
        run: |
          declare -r AUTHORS="$(git log $LAST_VERSION_TAG..HEAD --no-merges --oneline --format='%ae' 2>/dev/null | sort -u)"
          if [ -z "$AUTHORS" ]; then
            echo "Skipping auto-release. Since last release $LAST_RELEASE_TAG there were no new commits."
            echo ""
            echo "release=false" | tee -a $GITHUB_OUTPUT
            exit 0
          fi
          declare -r DEPENDABOT="$(echo "$AUTHORS" \
            | grep -E ".*dependabot\[bot\]@users.noreply.github.com$")"
          if [ -z "$DEPENDABOT" ]; then
            echo "Skipping auto-release. Since last release $LAST_RELEASE_TAG there were no dependabot commits."
            echo ""
            echo "Authors:"
            echo "$AUTHORS"
            echo ""
            echo "release=false" | tee -a $GITHUB_OUTPUT
            exit 0
          fi
          declare -r NO_BOTS="$(echo "$AUTHORS" \
            | grep -Ev ".*coditory\[bot\]@users.noreply.github.com$" \
            | grep -Ev ".*dependabot\[bot\]@users.noreply.github.com$")"
          if [ -n "$NO_BOTS" ]; then
            echo "Skipping auto-release. Since last release $LAST_RELEASE_TAG there were changes commited by non predefined bots."
            echo ""
            echo "Authors:"
            echo "$AUTHORS"
            echo ""
            echo "release=false" | tee -a $GITHUB_OUTPUT
            exit 0
          fi
          echo "Triggering release. Since last release $LAST_RELEASE_TAG there were only commits authored by recognized bots."
          echo ""
          echo "release=true" | tee -a $GITHUB_OUTPUT
