name: Release Auto

on:
  workflow_call:
    inputs:
      security-updates-only:
        type: boolean
        description: 'Check only for security updates'
        required: false
        default: false

jobs:
  coditory-check:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check.outputs.release }}
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required to deduce version from git tags
          fetch-depth: 0

      - name: Version
        id: version
        uses: coditory/version-action@v1
        with:
          snapshot: ${{ inputs.snapshot }}
          manual-version: ${{ inputs.version }}
          increment-section: ${{ inputs.section }}

      - name: Check commits
        id: check
        env:
          LAST_VERSION_TAG: "v${{ steps.version.outputs.version }}"
          SEC_UPDATES_ONLY: "${{ inputs.security-updates-only }}"
        run: |
          declare -r AUTHORS="$(git log $LAST_VERSION_TAG..HEAD --no-merges --oneline --format='%ae' 2>/dev/null | sort -u)"
          declare -r DEPENDABOT="$(echo "$AUTHORS" | grep -E ".*dependabot\[bot\]@users.noreply.github.com$")"
          declare -r NO_BOTS="$(echo "$AUTHORS" \
            | grep -Ev ".*coditory\[bot\]@users.noreply.github.com$" \
            | grep -Ev ".*dependabot\[bot\]@users.noreply.github.com$")"
          declare -r MESSAGES="$(git log $LAST_VERSION_TAG..HEAD --no-merges --oneline --format='%s' 2>/dev/null | sort -u)"
          declare -r IMPORTANT_UPDATES="$(echo "$MESSAGES" | grep -E " sec-updates " | grep -E " prod-dependencies " | grep -E " prod-dependencies-major ")"
          declare -r SEC_UPDATES="$(echo "$MESSAGES" | grep -E " sec-updates ")"
          decalre SKIP_CAUSE=""
          if [ -z "$AUTHORS" ]; then
            SKIP_CAUSE="Since last release $LAST_VERSION_TAG there were no new commits."
          elif [ -z "$DEPENDABOT" ]; then
            SKIP_CAUSE="Since last release $LAST_VERSION_TAG there were no dependabot commits." \
          elif [ -n "$NO_BOTS" ]; then
            SKIP_CAUSE="Since last release $LAST_VERSION_TAG there were changes commited by others." \
          elif [ -z "$IMPORTANT_UPDATES" ]; then
            SKIP_CAUSE="Since last release $LAST_VERSION_TAG there were no important changes." \
          elseif [ "$SECURITY_UPDATES_ONLY" == "true" ] && [ -z "$SEC_UPDATES" ]; then
            SKIP_CAUSE="Since last release $LAST_VERSION_TAG there were no security updates." \
          fi
          if [ -n "$SKIP_CAUSE" ]; then
            echo "Skipping auto release: $SKIP_CAUSE" | tee -a $GITHUB_STEP_SUMMARY
            echo ""
            echo "Authors: $(echo "$AUTHORS" | wc -l)"
            echo
            echo "release=false" | tee -a $GITHUB_OUTPUT
            exit 0
          fi
          echo "Triggering auto release. Since last release $LAST_VERSION_TAG there were only commits authored by trusted bots." \
            | tee -a $GITHUB_STEP_SUMMARY
          echo ""
          echo "release=true" | tee -a $GITHUB_OUTPUT
